name: Publish NuGet package

on:
  push:
    branches: main

env:
  BUILD_CONFIGURATON: Release

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}

  build:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
    - name: Build
      run: dotnet build --configuration $BUILD_CONFIGURATION
      
  test:
   runs-on: ubuntu-latest
   needs: [build]
   steps:
    - name: Test
      run: dotnet test --no-build --configuration $BUILD_CONFIGURATION
      
  publish:
    runs-on: ubuntu-latest
    needs: [test]
    steps:  
    - name: Pack
      run: dotnet pack --no-build --configuration $BUILD_CONFIGURATION --output ./nupkgs
    
    - name: Push NuGet package
      run: dotnet nuget push ./nupkgs/*.nupkg --skip-duplicate
    
