name: Publish NuGet package

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}

    - name: Build
      run: dotnet build --configuration Release
      
    - name: Test
      run: dotnet test --no-build
      
    - name: Pack
      run: dotnet pack --no-build --output ./nupkgs
    
    - name: Push NuGet package
      run: dotnet nuget push ./nupkgs/*.nupkg
    
